name: linux

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install qt5-qmake qtdeclarative5-dev
      # For tests
      - run: sudo apt-get install lz4 python3 xvfb

      - run: |
          mkdir tools
          cd tools
          # vasm (Atari)
          wget http://sun.hasenbraten.de/vasm/daily/vasm.tar.gz
          tar -xzf vasm.tar.gz
          cd vasm
          make CPU=m68k SYNTAX=mot -j 2
          cd ..
          # rgbasm (GameBoy)
          git clone https://github.com/gbdev/rgbds.git
          cd rgbds
          # v0.5 removes GLOBAL keyword
          git checkout tags/v0.4.2
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j 2
          cd ..
          # pasmo
          wget http://pasmo.speccy.org/bin/pasmo-0.5.4.beta2.tgz
          tar -xzf pasmo-0.5.4.beta2.tgz
          cd pasmo-0.5.4.beta2
          ./configure
          make -j 2
          cd ..
          mv pasmo-0.5.4.beta2 pasmo
          cd ..
          pwd
          ls
          echo ${PWD}
          # patch dirs
          echo "sed"
          sed -i "s,^vasmm =.*,vasmm=${PWD}/tools/vasm/vasmm68k_mot," Publish/publish_linux/trse.ini
          sed -i "s,^gameboy_rgbasm_dir =.*,gameboy_rgbasm_dir=${PWD}/tools/rgbasm/build/src," Publish/publish_linux/trse.ini
          sed -i "s,^pasmo =.*,pasmo=${PWD}/tools/pasmo/pasmo," Publish/publish_linux/trse.ini
          echo "cat"
          cat Publish/publish_linux/trse.ini
          echo "greps"
          grep vasmm Publish/publish_linux/trse.ini
          grep pasmo Publish/publish_linux/trse.ini
          grep gameboy_rgbasm_dir Publish/publish_linux/trse.ini
          echo "ls"
          ls ${PWD}/tools
          ls ${PWD}/tools/vasm/vasmm68k_mot
          ls ${PWD}/tools/rgbasm/build/src
          ls ${PWD}/tools/pasmo/pasmo
      - run: qmake TRSE.pro
      - run: make
      - name: Verify tutorials
        run: |
          mkdir bin
          cp trse bin/
          ln -s Publish/tutorials tutorials
          ln -s Publish/source/themes themes
          mkdir -p ~/.local/share/TRSE
          cp Publish/publish_linux/trse.ini ~/.local/share/TRSE/
          cd bin
          xvfb-run --auto-servernum python3 ../Publish/verify_all/verify_all.py `pwd`/trse
