name: linux

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install qt5-qmake qtdeclarative5-dev
      # For tests
      - run: sudo apt-get install lz4 python3

      - run: qmake TRSE.pro
      - run: make
      - run: |
          mkdir bin
          cp trse bin/
          ln -s Publish/tutorials tutorials
          mkdir -p ~/.local/share/TRSE
          cp Publish/publish_linux/trse.ini ~/.local/share/TRSE/
          cd bin
          python3 ../Publish/verify_all/verify_all.py `pwd`/trse

      # All the steps below are not necessary (for now) but document what needs
      # to be done for TRSE to work under linux.
      - run: ln -s Publish/tutorials tutorials
      - run: ln -s Publish/source/themes themes
      # Don't create the project_templates because it's already there
      - run: mkdir bin 
      - run: mv trse bin/
      # Now you're ready to run:
      # ./bin/trse
