name: linux

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install qt5-qmake qtdeclarative5-dev
      # For tests
      - run: sudo apt-get install lz4 python3

      - run: qmake TRSE.pro
      - run: make
      - name: Verify tutorials
        run: |
          mkdir bin
          cp trse bin/
          ln -s Publish/tutorials tutorials
          ln -s Publish/source/themes themes
          mkdir -p ~/.local/share/TRSE
          cp Publish/publish_linux/trse.ini ~/.local/share/TRSE/
          cd bin
          python3 ../Publish/verify_all/verify_all.py `pwd`/trse
