name: macx

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: jurplel/install-qt-action@v2
      - run: brew install libomp

      - run: qmake TRSE.pro
      - run: make -j 3

      - run: cd Publish/publish_mac && ./publish_mac.sh nightly
      - uses: ColinPitrat/update-release@master
        with:
          release: nightly
          message: Nightly build
          body: The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
          files: Publish/publish_mac/trse_osx.tar.gz
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build notification
        if: failed()
        uses: adamkdean/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: #bugs
          text: "[GitHub Actions Notification] MacOS build failed: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"
