name: macx

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: brew update
      - run: brew install qt

      - run: qmake TRSE.pro
      - run: make

      # All the steps below are not necessary (for now) but document what needs
      # to be done for TRSE to work under MacOS X.
      - run: ln -s Publish/tutorials tutorials
      - run: ln -s Publish/source/themes themes
      # Don't create the project_templates because it's already there
      - run: mkdir bin 
      - run: mv trse bin/
      # Now you're ready to run:
      # ./bin/trse
