name: nightly

on:
  schedule:
    # TODO(ColinPitrat): change back to '42 21 * * *'
    - cron: '*/5 21 * * *'

# Triggers the nightly builds by tagging master branch
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: false
          tag_name: "nightly"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "nightly"
