name: windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: jurplel/install-qt-action@v2
      - run: qmake TRSE.pro
      - run: cat Makefile.Release
      - run: make
      # All the steps below are not necessary (for now) but document what needs
      # to be done for TRSE to work under linux.
      - run: copy TRSE/Publish/source/themes TRSE/Release/
      # This should be a symbolic link
      - run: copy TRSE/Publish/tutorials TRSE/Release/
      - run: copy TRSE/Units TRSE/Units/
      # Now you're ready to run:
      # ./bin/trse
